### ISSUE TITLE
Use nc from MacOS instead

### ISSUE THREAD

**Issue by jturner** [zetashift/unison-zed#2]
Could this just use the builtin `nc` from MacOS instead? Why require `nmap` to be installed for `ncat`? Even via the `apt-get` example you have to pick the OpenBSD or Traditional version which gets you a `nc` binary...

**Comment by zetashift** [comment]
Hi! When starting this I googled `ncat` vs `nc` and I read somewhere that `ncat` had several improvements over `nc`. Since I use `nix`(on Linux and Mac), I simply went the `nmap` version without thinking too much about it.

I also didn't know `nc` came as a builtin in MacOS! I'll try to whip up a PR that uses that binary.

Though ideally, Zed's extension API would allow an user to specify the language server config more like `helix`.

**Comment by jturner** [comment]
> Hi! When starting this I googled `ncat` vs `nc` and I read somewhere that `ncat` had several improvements over `nc`. Since I use `nix`(on Linux and Mac), I simply went the `nmap` version without thinking too much about it.
> 
> I also didn't know `nc` came as a builtin in MacOS! I'll try to whip up a PR that uses that binary.
> 
> Though ideally, Zed's extension API would allow an user to specify the language server config more like `helix`.

That would be awesome. I think the `nmap` version is probably an improvement, but for the basic usage here maybe it doesn't really matter 🤷 .

**Comment by zetashift** [comment]
GitHub auto-closed this issue, the new version still needs to be released to the Zed extension repo, I'll try to get it in!

**Comment by jturner** [comment]
> GitHub auto-closed this issue, the new version still needs to be released to the Zed extension repo, I'll try to get it in!

Awesome, thanks again!
